/** @format */

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  Heading,
  Flex,
  Button,
  Text,
  Center,
  List,
  ListItem,
  ListIcon,
  Stat,
  StatLabel,
  StatHelpText,
  StatNumber,
  Box,
  Icon,
} from "@chakra-ui/react";
import {
  FaAddressBook,
  FaArrowAltCircleRight,
  FaArrowCircleRight,
  FaArrowRight,
  FaCheckCircle,
  FaCheckSquare,
  FaMoneyBill,
  FaRegAddressCard,
  FaUserFriends,
  FaUserGraduate,
} from "react-icons/fa";

import { GiPartyPopper, GiUpgrade } from "react-icons/gi";

import { SiMathworks } from "react-icons/si";
import { MdEvent } from "react-icons/md";

import { BsPersonSquare } from "react-icons/bs";

const reasonsToJoin = [
  {
    title: "Improved Grades",
    description:
      "By sharing and building your math skills through Mu Alpha Theta, you are on your way to get better grades.",
    icon: <GiUpgrade size={40} color='#63B3ED' />,
  },
  {
    title: "Stronger Profile",
    description:
      "Joining Mu Alpha Theta will not only be prestigious for your resume, but also allow you to improve your SAT/ACT/AP scores.",
    icon: <FaUserGraduate size={40} color='#63B3ED' />,
  },
  {
    title: "Tons of Fun",
    description:
      "The best part about joining Mu Alpha Theta is that Math is fun! We make gingerbread houses, fly fake parachutes and host many other fun events!",
    icon: <GiPartyPopper size={40} color='#63B3ED' />,
  },
  {
    title: "New Friends",
    description:
      "Mu Alpha Theta creates an environment where you can easily make friends through collaboration and fun events.",
    icon: <FaUserFriends size={40} color='#63B3ED' />,
  },
];

const nationalReqs = [
  {
    title: "4 or more semesters of Math courses completed",
    description:
      "Includes Algebra I/II, Geometry, College Algebra, Pre-Calculus, and/or Calculus OR 1 or more semester of Pre-Calculus Pre-AP or higher completed.",
  },
  {
    title: "Currently enrolled in a GT, Pre-AP or AP mathematics course",
    description: null,
  },
  {
    title: "87.0 or higher unweighted average in all mathematics courses taken",
    description: "Effective Fall 2018",
  },
];

const genReqs = [
  {
    title:
      "Maintain an unweighted GPA of 87.0 or above for all mathematics courses taken",
    description: null,
    icon: <GiUpgrade size={40} color='#63B3ED' />,
  },
  {
    title:
      "Pay membership due of $35 for new inductees or $25 for returning members or associates",
    description: null,
    icon: <FaMoneyBill size={40} color='#63B3ED' />,
  },
  {
    title:
      "Attend 3 academic events and at least 3 Mu Alpha Theta approved events by the end of every semester",
    description: null,
    icon: <MdEvent size={40} color='#63B3ED' />,
  },
  {
    title: "Attend all meetings",
    description:
      "If you miss a meeting, you must submit excuse note within one week to the Google classroom form",
    icon: <BsPersonSquare size={40} color='#63B3ED' />,
  },
];

const reasonsComponents = reasonsToJoin.map((reason) => (
  <Stat
    w={400}
    h={200}
    p={10}
    m={10}
    bgColor='gray.800'
    borderRadius={30}
    display='flex'
    alignItems='center'
    justifyContent='center'>
    {reason.icon}
    <StatNumber color='whiteAlpha.700'>{reason.title}</StatNumber>
    <StatHelpText color='whiteAlpha.700'>{reason.description}</StatHelpText>
  </Stat>
));

const nationalReqsComponents = nationalReqs.map((req, index, arr) => (
  <Stat
    bgColor='gray.800'
    color='whiteAlpha.800'
    p={8}
    borderRadius={20}
    alignSelf='center'
    maxWidth={1400}
    w={1000}
    minWidth={600}
    mt='20px'
    mb={index === arr.length - 1 ? 0 : 20}>
    <StatLabel>Requirement #{index + 1}</StatLabel>
    <StatNumber>{req.title}</StatNumber>
    {req.description !== null ? (
      <StatHelpText>{req.description}</StatHelpText>
    ) : (
      <></>
    )}
  </Stat>
));

const genReqComponents = genReqs.map((req, index, arr) => (
  <Stat
    bgColor='gray.800'
    color='whiteAlpha.800'
    p={8}
    borderRadius={20}
    width={1200}
    mt={"20px"}
    mb={index === arr.length - 1 ? 10 : 20}
    key={req.title}>
    {req.icon}
    <StatNumber>{req.title}</StatNumber>
    {req.description !== null ? (
      <StatHelpText>{req.description}</StatHelpText>
    ) : (
      <></>
    )}
  </Stat>
));

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Flex p={4}>
          <SiMathworks size={48} color='#3182CE' />
          <Heading color='black' ml={2}>
            {" "}
            Reagan Mu Alpha Theta{" "}
          </Heading>
        </Flex>
        <div className={styles.hero}>
          <Heading
            size='4xl'
            color='#72b9f6'
            bgGradient='linear(to-r, blue.600, blue.500)'
            bgClip='text'
            w={1000}
            h={180}
            textAlign='center'>
            {" "}
            Your favorite subject does not have to be Math
          </Heading>
          <Text fontSize='2xl' color='gray' textAlign='center' w={1000}>
            Mu Alpha Theta is more than just a Math Honor Society. We are a team
            that has fun competing and representing Reagan High School at Math
            tournaments and events.
          </Text>
          <Flex direction='row' mt={10} justifyContent='center'>
            <Button
              size='lg'
              colorScheme='blue'
              rightIcon={<FaArrowRight />}
              padding={8}>
              Apply
            </Button>
            <Button
              size='lg'
              colorScheme='blue'
              variant='outline'
              leftIcon={<FaAddressBook />}
              p={8}
              ml={10}>
              Contact
            </Button>
          </Flex>
        </div>
        <Box
          display='flex'
          alignItems='center'
          flexDir='column'
          bgColor='blue.100'
          width='100%'>
          <Heading textAlign='center' color='blackAlpha.900' mt={10} mb={5}>
            A Meaningful Commitment
          </Heading>
          <Text fontSize='2xl' color='blackAlpha.700'>
            What you will get
          </Text>
          <Flex>{reasonsComponents.slice(0, 2)}</Flex>
          <Flex>{reasonsComponents.slice(2, 4)}</Flex>
        </Box>
        <Box bgColor='blue.200' width='100%'>
          <Heading textAlign='center' color='blackAlpha.900' mt={10} mb={5}>
            National Membership
          </Heading>
          <Text textAlign='center' fontSize='xl' color='blackAlpha.700'>
            If you meet the requirements below, apply today to join the national
            chapter! If not, you can still join as an associate member.
          </Text>
          <Box display='flex' flexDir='column' justifyContent='center'>
            {nationalReqsComponents}
          </Box>
          <Text
            textAlign='center'
            fontSize='xl'
            color='blackAlpha.700'
            pl={20}
            pr={20}
            pt={10}
            pb={10}>
            If you don't meet the above requirements and want to join as an
            associate, you must have completed one year of algebra, or its
            equivalent, and must be currently enrolled in a higher math course.
            You can join most fun activities and math tournaments as an
            associate! The only difference is that you won't be an official
            national member.
          </Text>
        </Box>
        <Box
          bgColor='blue.100'
          width='100%'
          display='flex'
          flexDir='column'
          alignItems='center'>
          <Heading textAlign='center' color='blackAlpha.900' mt={10} mb={5}>
            {" "}
            Member and Associate Requirements
          </Heading>

          {genReqComponents}
        </Box>
        <Box as='section' bgColor='blue.900' w='100%'>
          <Box
            maxW='2xl'
            mx='auto'
            px={{ base: "6", lg: "8" }}
            py={{ base: "16", sm: "20" }}
            textAlign='center'>
            <Heading
              as='h2'
              size='3xl'
              fontWeight='extrabold'
              letterSpacing='tight'
              color='whiteAlpha.700'>
              Ready to Grow?
            </Heading>
            <Text mt='4' fontSize='lg' color='whiteAlpha.700'>
              Apply today and buckle up for the adventure of a lifetime.
            </Text>
            <Button
              mt='8'
              as='a'
              href='#'
              size='lg'
              colorScheme='blue'
              fontWeight='bold'>
              Apply
            </Button>
          </Box>
        </Box>
      </main>
    </div>
  );
}
